---
- name: Provision workstation

  hosts: all
  connection: local
  pre_tasks:
    - name: 'Update APT'
      apt:
        autoclean: true
        autoremove: true
        cache_valid_time: 0
        update_cache: true
        install_recommends: false
      when: ansible_os_family == 'Debian'
  roles:
    - workstation
  become: yes
